server:
  port: 8086

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book
          uri: lb://book
          predicates:
            - Path=/api/book/**, /api/author/**, /api/book_star/**
        - id: user-favourite
          uri: lb://user-favourite
          predicates:
            - Path=/api/user-favourite/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/user/**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
