server:
  port: 8086

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book
          uri: lb://book
          predicates:
            - Path=/api/book/**, /api/author/**. /api/book_star/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/user/**